version: "3"

services:
  cluster-bsc-rpc: # This is the bootstrap node
    image: bsc-geth:docker-local
    env_file: .env
    ports:
      - 8545:8545
    environment:
      NODE_ID: bsc-rpc
    volumes:
      - ./storage/bsc-rpc:/root/.ethereum
      - ./scripts:/scripts
      - ./config:/config
    command: ash /scripts/bsc-rpc.sh

  cluster-bsc-validator1:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator1
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator1:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh

  cluster-bsc-validator2:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator2
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator2:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh

  cluster-bsc-validator3:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator3
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator3:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 99.99.0.0/16
